### ISSUE TITLE
username and repos typography looks bad. 

### ISSUE THREAD

**Issue by Nnaji-Victor** [Nnaji-Victor/HacktoberMagazine#4]

**Comment by wptechprodigy** [comment]
What do you mean by username and repos typography looks bad?

**Comment by Nnaji-Victor** [comment]
The username and repo typography does  not have any font so it looks kinda odd from the other texts on the card

**Comment by Sunithack1** [comment]
Hi @Nnaji-Victor ,

Is there any specific font in your mind for username and repo? I can work on it

**Comment by Nnaji-Victor** [comment]
No, play around with any font of your choice

**Comment by Sunithack1** [comment]
Okay. Thanks

**Comment by Sunithack1** [comment]
I have changed the fonts. Please let me know if you need any changes
