### ISSUE TITLE
Same card appears twice !

### ISSUE THREAD

**Issue by RocktimSaikia** [Nnaji-Victor/HacktoberMagazine#46]
Most of the cards seems to be appearing twice >

![bug2](https://user-images.githubusercontent.com/33410545/66284210-a944f180-e87b-11e9-8105-f670736c3b87.png)

I think some of the people making pull requests made these mistakes.Please fix it. And please review the pull request more carefully before merging them. Thanks

**Comment by Nnaji-Victor** [comment]
Fixed!. 😎
